{% set name = "tidynamics" %}
{% set version = "1.1.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "103874edd79dc64a0c7b765f51200926822e74df63703acb6c630a8167dbcfa2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - numpy

test:
  imports:
    - tidynamics

about:
  home: ' https://pypi.python.org/pypi/tidynamics'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tiny package to compute dynamics correlations
  description: |
    tidynamics performs the computation of mean-square displacements and correlation functions.
    tidynamics implements the so-called Fast Correlation Algorithm proposed by Kneller and others for the nMOLDYN analysis program.
    tidynamics depends only Python and NumPy.
  doc_url: 'http://lab.pdebuyl.be/tidynamics/'
  dev_url: 'https://github.com/pdebuyl-lab/tidynamics'

extra:
  recipe-maintainers:
    - pdebuyl
