{% set name = "tidynamics" %}
{% set version = "1.1.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '103874edd79dc64a0c7b765f51200926822e74df63703acb6c630a8167dbcfa2'

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - tidynamics

about:
  home: ' https://pypi.python.org/pypi/tidynamics'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tiny package to compute dynamics correlations
  description: |
    tidynamics performs the computation of mean-square displacements and correlation functions.
    tidynamics implements the so-called Fast Correlation Algorithm proposed by Kneller and others for the nMOLDYN analysis program.
    tidynamics depends only Python and NumPy.
  doc_url: 'http://lab.pdebuyl.be/tidynamics/'
  dev_url: 'https://github.com/pdebuyl-lab/tidynamics'

extra:
  recipe-maintainers:
    - pdebuyl
