travis:
  secure:
    BINSTAR_TOKEN: izZtmQTViZcRsaFmXRvl+SSv1V8Pn0G0uHmxPt8YpORl/6XwX4pbalovH4pQQ5A/fq78iXaaWsvAd0geahjnEIzFXwEcgqpRE/APUCx2chEk29O1T1rEJUMLAAbg27ZNufgZrmuC0x9C796EyRkiOWWCdVp+HF9WzJgkW635s6MrLOFn5IQ7hN9lDpU1+QFHa4r1cxmfyrQajanp8GMwkdgeoo5BtPe3nyRrVXMjUOvOhmqkK7Qm7XBgI81jTLDlarqX7/GLzcXxPVj9xeVABM46Y5s9LfCdvZAB2NV0TXQVDBbQHiMp4R0Kdv5MC8MVU07ppd6aR8db0BTZDAmo6PkKhTn3trcVWg9TqSWT8maKhIO1RBJyaLgCLVaW7RlPqmh7qaJqPMBGOsU4kTCPG3e/ZYouLIr8JnI+kuN9Jc7BBt2n36IlDT2gT4qmS22djbbEKALjSRFYdse+SR8Fu0O/GBd5PZQ1Wc8J9qTIH6cRCmRqaveXSGvaba7BVOFyuRqmkXwfQE4Z36QV6MliPUTqxLF8qf0xhrAkMfgfUr6tIGERbEXlKp31BgFewdypVRI3rpu7/n910irUjtRGHF6jnsTxnUJzgCQOeItALs+Be6r2lT5QFQxLHgQkvAMfifICQjgrVRdlLwjuHFbF82mCyz9swT4uRhsLa8AqjN0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
