travis:
  secure:
    BINSTAR_TOKEN: GXIOw+CdP+njN+OKpgjDrlUAtocheEBclVEzeKxU7GgCcdA4NzWsd4M9aDTQKc8pGNc65EdVIhUBu/iPFHTlEdXnEz2Gp9YHLBaYayJKZD94EtXoz3xSU0FOMW1fCVVd8g1pFl3ZPoEthnprQZ9e/az61u9EXXeGL+paB40mUlr0xl+5Gd+XJ3eOmd4mdvbByAIYyyrzyLmV8JYF7LILtkcarP6FalsovG535kGSQrK6MKbxkwZ00Hbiw9qX2/RHdHYOgYwWNGMDG31isMKXE6Nks3m296i4yjPAy43liw32CYXVifBGGYvkCfzxPDyZw4cQ4TJ29dWXShCyo+e/jnejnj9aexVDczl+Sjy/MaHox94LZCFF2N/pQ6PVBA890X2XvLKlyR6fN4Fx7ziOjJDIguMBJE4wMiEx0hT1W9gXNzmCoxdV9SbiiD7LYsjxZzYCGq+PU/lJjxxror0glx/apHlvq2oJmnY62aqHHXAFP5KFIIAIqqGKK5quw5zm2eJi372FNjEvHcHSzpzdjMZuAKyPdYsPS6vez7cg6/meUDzrVgGZuWUReWrcJzQmRPCf9nkhE5VUyEk8GaNP1E0YRNaEVS31gJte7NVDsuccFMUY2O55q2I8rFdVDjFntuiDef/Qp5wZ/5mQfxQPMH6LLwe5pL35KJj+PCq7N9E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
